/* ILFUNZ.H					G. Toffoli, 22.05.89
  28.10.88 GT - vers. 3 LC
   dichiarazioni di funzioni di tipo diverso da INT

  NON METTERCI  ILARGVAR.I  anche se esiste.

*/

#include "ILANALIS.I"
#include "ILARGVA2.I"	/* scritto a mano per numero arg. var. */
#include "ILASM.I"
#include "ILCATENE.I"
#include "ILCONTRO.I"
#include "ILDEF.I"
#include "ILDIZION.I"
#include "ILFOGLIO.I"
#include "ILFLUSSI.I"
#include "ILGLOSSE.I"
#include "ILINIC.I"
#include "ILLOGICA.I"
#include "ILMAIN.I"
#include "ILMONDO.I"
#include "ILNODI.I"
#include "ILNUMERI.I"
#include "ILPARLIS.I"
#include "ILQUADRO.I"
#include "ILSCRIVI.I"
#include "ILSPAZIO.I"
#include "ILSTACK.I"
#include "ILTARTA.I"
#include "ILTESTO.I"
#include "ILUTIL.I"
#include "ILVIEW.I"
