//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Iperlogo.rc
//
#define IDR_MAINFRAME                   2
#define ID_PEN                          3
#define IDRESET                         3
#define IDALL                           3
#define IDREGISTER                      3
#define IDS_STRING3                     3
#define IDS_VERSION                     3
#define ID_BK                           4
#define IDSELECTION                     4
#define ID_FILL                         5
#define IDCANCE                         6
#define IDD_ABOUTBOX                    100
#define IDD_IPERLOGO_FORM               101
#define IDD_LINE_DIALOG                 102
#define IDD_BROWSER_DIALOGBAR           103
#define IDR_TURTLE                      104
#define IDD_MODELESS                    105
#define IDD_MODAL                       106
#define IDB_BITMAP16                    107
#define IDB_BITMAP16M                   108
#define IDB_BITMAP256                   109
#define IDD_INPUT                       110
#define IDD_KEYBOARD                    111
#define IDR_EDITOR                      114
#define IDR_WEB                         115
#define IDD_TURTLE_STATUS               116
#define IDR_TURTLE_OBJ                  116
#define IDD_ACTIVE_AREA                 117
#define IDD_MAIN_STATUS                 118
#define IDD_WELCOME                     119
#define IDD_SELPROC                     120
#define IDD_TURTLE_NEW                  121
#define IDB_BITMAP1                     121
#define IDD_REGISTER                    122
#define IDB_BITMAP2                     123
#define IDD_USAGE                       123
#define IDB_BITMAP3                     124
#define IDD_PALETTE                     124
#define IDR_ACCELERATOR1                126
#define IDD_DIALOG1                     134
#define IDD_SELGLOSS                    135
#define IDR_TOOLBAR1                    145
#define IDD_NMUI                        150
#define IDC_LIST1                       1000
#define IDC_EDIT1                       1001
#define IDC_EXEC                        1002
#define IDC_TRACE                       1003
#define IDC_PAUSE                       1004
#define IDC_LINE_EDIT                   1004
#define IDC_EXEC2                       1004
#define IDC_HALT                        1005
#define IDC_RESET                       1006
#define IDC_YELD                        1007
#define IDC_PEN_STATU                   1007
#define IDC_WIN_STATUS                  1007
#define IDC_STATUS                      1008
#define IDC_PEN_CONTACT1                1008
#define IDC_PEN_STATUS                  1008
#define IDC_PEN_WIDTH1                  1009
#define IDC_PEN_STYLE1                  1010
#define IDC_PEN_CONTACT2                1011
#define IDC_PEN_STYLE2                  1012
#define IDC_AREA_YHIGH                  1012
#define IDC_PEN_WIDTH2                  1013
#define IDC_AREA_YLOW                   1013
#define IDC_YHIGH                       1014
#define IDC_NODES_STATUS                1014
#define IDC_FONT_SIZE1                  1015
#define IDC_YLOW                        1015
#define IDC_FONT_WEIGHT1                1016
#define IDC_XLOW                        1016
#define IDC_FONT_NAME2                  1017
#define IDC_AREA_XLOW                   1017
#define IDC_FONT_WEIGHT2                1018
#define IDC_XHIGH                       1018
#define IDC_FONT_SIZE2                  1019
#define IDC_AREA_XHIGH                  1019
#define IDC_PEN_FONT                    1020
#define IDC_TURTLE_POS1                 1021
#define IDC_TURTLE_HEADING1             1022
#define IDC_TURTLE_VISIBILITY1          1023
#define IDC_WIN_POS                     1023
#define IDC_TURTLE_POSX                 1024
#define IDC_TURTLE_VISIBILITY2          1025
#define IDC_TURTLE_HEADING2             1026
#define IDC_PEN_TURTLE                  1027
#define IDC_COLOR_PEN1                  1028
#define IDC_COLOR_FLOOD1                1029
#define IDC_COLOR_SCREEN1               1030
#define IDC_COLOR_PENG                  1031
#define IDC_NODES_TOTAL                 1032
#define IDC_TURTLE_HEADING3             1032
#define IDC_WIN_DIM                     1032
#define IDC_NODES_USED                  1033
#define IDC_WIN_POSX                    1033
#define IDC_PEN_COLOR                   1034
#define IDC_WIN_MODE                    1034
#define IDC_TURTLE_POSY                 1035
#define IDC_COLOR_PENR                  1036
#define IDC_COLOR_PENB                  1037
#define IDC_COLOR_FLOODG                1038
#define IDC_COLOR_FLOODR                1039
#define IDC_COLOR_FLOODB                1040
#define IDC_COLOR_SCREENG               1041
#define IDC_COLOR_SCREENR               1042
#define IDC_COLOR_SCREENB               1043
#define IDC_NODES_FREE                  1044
#define IDC_WIN_POSY                    1044
#define IDC_NODES_TOTAL2                1045
#define IDC_WIN_DIMX                    1045
#define IDC_NODES_USED2                 1046
#define IDC_WIN_DIMY                    1046
#define IDC_NODES_FREE2                 1047
#define IDC_VIEW_YLOW                   1047
#define IDC_VIEW_YHIGH2                 1048
#define IDC_OPTIONS_STATUS              1049
#define IDC_VIEW_YLOW2                  1049
#define IDC_OPTIONS_CASE                1050
#define IDC_VIEW_XLOW                   1050
#define IDC_OPTIONS_TRACE               1051
#define IDC_VIEW_XLOW2                  1051
#define IDC_OPTIONS_BOH                 1052
#define IDC_VIEW_XHIGH                  1052
#define IDC_VIEW_XHIGH2                 1053
#define IDC_VIEW_YHIGH                  1054
#define IDC_VIEW_STATUS                 1055
#define IDC_VIEW_PIXEL                  1056
#define IDC_VIEW_PIXELX                 1057
#define IDC_SELPROC                     1057
#define IDC_VIEW_PIXELY                 1058
#define IDC_TURTLE_NAME2                1059
#define IDC_VIEW_NAME                   1061
#define IDC_VIEW_NAME2                  1062
#define IDC_RICHEDIT1                   1063
#define IDC_EDIT_CODE                   1064
#define IDC_TEXT_CODE                   1065
#define IDC_TEXT_STATUS                 1066
#define IDC_TEXT_COMPANY                1067
#define IDC_EDIT_COMPANY                1068
#define IDC_TEXT_NAME                   1069
#define IDC_EDIT_NAME                   1070
#define IDC_TEXT_SERIAL                 1071
#define IDC_EDIT_SERIAL                 1072
#define IDC_TEXT_ACCESS                 1073
#define IDC_EDIT_ACCESS                 1074
#define IDC_TEXT_TIMES                  1075
#define IDC_TEXT_TOTAL                  1076
#define IDC_TEXT_LAST                   1077
#define IDC_EDIT_TOTAL                  1078
#define IDC_EDIT_LAST                   1079
#define IDC_EDIT_TIMES                  1081
#define IDC_SET                         1083
#define IDC_EDIT2                       1084
#define ID_GO                           1086
#define IDC_LIST_CAT                    1088
#define IDC_LIST_ENV                    1089
#define IDC_STATIC_INI                  1090
#define IDC_STATIC_CAT                  1091
#define IDC_STATIC_ENV                  1092
#define IDC_TEXT_INI                    1093
#define IDC_CHECK_NOALIAS               1094
#define IDC_VIEW_MODE2                  1095
#define IDC_CHECK_SUPERLOGO             1096
#define IDC_WIEW_WIN                    1096
#define IDC_CHECK_IPERLOGO              1097
#define IDC_NM_IPADDRESS                1097
#define ID_ZOOM_IN                      32771
#define ID_IMPORTSYMBOL                 32775
#define ID_ZOOM_OUT                     32780
#define ID_ZOOM_NORMAL                  32781
#define ID_BITMAP_NEW                   32783
#define ID_BITMAP_LOAD                  32784
#define ID_BITMAP_SAVE                  32785
#define ID_BITMAP_SAVEAS                32786
#define ID_BITMAP_PRINT                 32788
#define ID_PRINT_SETUP                  32789
#define ID_BITMAP_ACTIVEAREA            32790
#define ID_FILE_EDIT                    32791
#define ID_FILE_ERASE                   32792
#define ID_FILE_LOAD                    32793
#define ID_EDIT_SELECTALL               32795
#define ID_EDIT_DELETE                  32796
#define ID_SEARCH_FIND                  32797
#define ID_SEARCH_FINDNEXT              32798
#define ID_FILE_EXIT                    32799
#define ID_FILE_EXECANDEXIT             32800
#define ID_SEARCH_REPLACE               32801
#define ID_SET_FONT                     32802
#define ID_HELP_EDITOR                  32804
#define ID_HELP_TOPIC                   32805
#define ID_TEST_SELECTION               32806
#define ID_TEST_ALL                     32807
#define ID_HELP_TUTORIAL                32808
#define ID_HELP_DEMO                    32809
#define ID_HELP_EXAMPLES                32810
#define ID_HELP_RELEASE                 32811
#define ID_SET_PENSIZE                  32812
#define ID_SET_PENCOLOR                 32813
#define ID_SET_FLOODCOLOR               32814
#define ID_SET_SCREENCOLOR              32815
#define ID_WINDOWS_NEW                  32816
#define ID_WINDOWS_TURTLE               32816
#define ID_TURTLESTATUS_SHOW            32817
#define ID_TURTLESTATUS_REFRESH         32818
#define ID_TURTLESTATUS_HIDE            32819
#define ID_WINDOWS_WINDOW               32821
#define ID_W_2                          32822
#define ID_W_3                          32823
#define ID_W_4                          32824
#define ID_W_5                          32825
#define ID_W_6                          32826
#define ID_W_7                          32827
#define ID_W_8                          32828
#define ID_W_9                          32829
#define ID_W_10                         32830
#define ID_FILE_PRINTSETUP              32831
#define ID_OPTION_SHOWSTATE             32832
#define ID_OPTION_TRACE                 32833
#define ID_EXEC                         32834
#define ID_OPTION_SHOWSTATUS            32835
#define ID_HELP_SEARCH                  32836
#define ID_VIEW_CENTER                  32837
#define ID_HELP_TURTLE                  32838
#define ID_FILE_SAVEAS                  32839
#define ID_FILESAVE                     32840
#define ID_WINDOWS_EDITOR               32841
#define ID_FILE_EDITPROC                32842
#define ID_FILE_CLEAR                   32844
#define ID_HALT                         32845
#define ID_PAUSE                        32846
#define ID_OPTION_FONT                  32847
#define ID_OPTION_CASE                  32848
#define ID_IMPOSTA_SPESSOREPENNA        32851
#define ID_SET_PENPLUS                  32853
#define ID_SET_PENMINUS                 32854
#define ID_OPTION_ECO                   32856
#define ID_OPTION_PROMPT                32857
#define ID_OPTION_ECOINT                32858
#define ID_MENUITEM32859                32859
#define ID_SELECT_TURTLE                32860
#define ID_REGISTER                     32861
#define ID_SELECT                       32862
#define ID_EDIT_SELECT                  32863
#define ID_SET_PALETTE                  32864
#define ID_OPTION_PROFILE               32865
#define ID_EDIT_FILL                    32866
#define ID_EDIT_RIEMPI                  32866
#define ID_EDIT_SELECTAREA              32867
#define ID_WINDOWS_PLAYER               32872
#define ID_WINDOWS_BROWSER              32873
#define ID_W_11                         32874
#define ID_W_12                         32875
#define ID_W_13                         32876
#define ID_W_14                         32877
#define ID_W_15                         32878
#define ID_W_16                         32879
#define ID_W_17                         32880
#define ID_W_18                         32881
#define ID_W_19                         32882
#define ID_W_20                         32883
#define ID_HELP_BROWSER                 32884
#define ID_FILE_PRINT2                  32885
#define ID_FILE_NEW2                    32886
#define ID_NAVIGATE_BACK                32887
#define ID_NAVIGATE_STOP                32888
#define ID_NAVIGATE_RELOAD              32889
#define ID_FILE_GO                      32890
#define ID_NAVIGATE_HOME                32891
#define ID_NAVIGATE_FORWARD             32892
#define ID_VIEW_FONTS_SMALLEST          32896
#define ID_VIEW_FONTS_SMALL             32897
#define ID_VIEW_FONTS_MEDIUM            32898
#define ID_VIEW_FONTS_LARGE             32899
#define ID_VIEW_FONTS_LARGEST           32900
#define ID_SELECT_EDITOR                32901
#define ID_SELECT_BROWSER               32902
#define ID_BUTTON32904                  32904
#define ID_HELP_GLOSSARY                32905
#define ID_EDIT_TAGLIA                  32906
#define ID_EDIT_COPIA                   32907
#define ID_EDIT_INCOLLA                 32908
#define ID_EDIT_BUTTA                   32909
#define ID_IL_SYMBOL_LOAD               32911
#define ID_IL_EDGE_CREATE               32912
#define ID_IL_EDGE_INVERT               32913

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32914
#define _APS_NEXT_CONTROL_VALUE         1097
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
